name: Update GitHub Stars

# 定时每天触发（UTC 零点），也可以手动触发
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update-stars:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Fetch GitHub star counts
      run: |
        npm ci
        node scripts/fetch-stars.js
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Commit updated galaxy.json
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add galaxy.json
        git diff --quiet && echo "No changes to commit" || git commit -m "chore: update GitHub star counts"
        git push
